### ISSUE TITLE
Theer is Problem in Code Line no 3

### ISSUE THREAD

**Issue by ShrutiSinhaa** [sankarpothukuchi/AZ-400#1]
Hi I have seen the missiiong syntax
![ad1](https://user-images.githubusercontent.com/53403148/82167919-e164e600-98da-11ea-8282-61fb2a44782c.jpg)

**Comment by sankarpothukuchi** [comment]
Thank you for the update

**Comment by ShrutiSinhaa** [comment]
OK lets close the cissue

**Comment by sankarpothukuchi** [comment]
Ok, I am closing the issue
